/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Standard': '标准',
    'Stripe Color': '条纹颜色',
    'Upgrades': '升级',
    'Tutorial': '教程',
    'Visit my Website': '访问我的网站',
    'Your Team': '你的团队',
    'Zalgo': '扎尔戈',
    'Team Settings': '团队设置',
    'Adjust the Speed of the Game': '调整游戏速度',
    'Aggressiveness': '红牌率',
    'always restart': '总是重启',
    'and on new Seasons.': '以及新赛季。',
    'cookies or storage': 'Cookie或本地存储',
    'Download Savegame': '下载游戏存档',
    'Each Player has 4 Stats': '每个球员有4个属性',
    'Engineering': '工程符号',
    'Exit Tutorial': '退出教程',
    'Export Game': '导出存档',
    'Game Settings': '游戏设置',
    'Football': '足球',
    'HARD RESET': '硬重置',
    'Idle Football Manager': '足球经理放置',
    'Import Game': '导入存档',
    'Letters': '字母',
    'League': '联盟',
    'Market': '市场',
    'Match Autoplay': '自动进行比赛',
    'Mixed engineering': '混合工程',
    'Mixed scientific': '混合科学',
    'new Players': '新球员',
    'Player Market': '球员市场',
    'Prime': '素数',
    'Restart Tutorial': '重启教程',
    'Roman': '罗马',
    'Save Management': '保存管理',
    'Scientific': '科学计数法',
    'Sides': '双方',
    'Match': '比赛',
    'Team': '团队',
    'Brackets': '括号',
    'Clock': '时钟',
    'Colors': '颜色',
    'Dots': '圆点',
    'Blind': '盲文',
    'Bar': '酒吧',
    'Hex': '十六进制',
    'Icon': '图标',
    'Imperial': '英制',
    'Infinity': '无限',
    'Logarithm': '对数',
    'Refill Team after Match': '赛后补充球员',
    'Social': '社交',
    'Strategy': '策略',
    'STA': '耐力',
    'Move from Team': '离开团队',
    'My Football Club': '我的足球俱乐部',
    'Match Rewards': '比赛奖励',
    'Play next Match': '进行下一场比赛',
    'Recommendationheim Warriors': '推荐海战勇士',
    'Richheim United': '里希海姆联',
    'Screwdorf Kickers': '斯卡特多夫踢球者',
    'Start': '开始',
    'Teamfort Dreamers': '梦幻之队',
    'Energy Drink': '能量饮料',
    'Soccer': '足球',
    'save if': '保存如果',
    'Unlock the Stadium': '解锁体育场',
    'Someone\'s watching': '有人在看',
    'Games': '游戏',
    'Upgradealicious': '可升级',
    'Very Famous': '非常有名',
    'Win your first match': '赢得你的第一场比赛',
    '→ Play next Match': '→ 进行下一场比赛',
    'Market Strategy': '市场策略',
    'Match Ended': '比赛结束',
    'Move to Team': '加入团队',
    'You are already in a Match.': '您已经在比赛中。',
    'Kinda Famous': '金田名品',
    'Goals': '进球',
    'Number Format': '数字格式',
    'often': '经常',
    'Cancer': '癌症',
    'Stadium': '体育场',
    'Stadium Capacity': '体育场容量',
    'Pricing Tactics': '定价策略',
    'Attack': '攻击',
    'Defense': '防御',
    'Stamina': '耐力',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '→ Modified by Stamina': '→ 根据耐力变化',
    '🏟 Your Stadium': '🏟 你的体育场',
    'The Famous Factor': '著名因素',
    'More people decide to become a fan.': '越来越多的人决定成为球迷。',
    'Increase the Price for each Ticket. Don\'t worry, this won\'t decrease attendance.': '增加每张票的价格。 不用担心，这不会减少出勤率。',
    'Increase the Amount of people that can watch the match at once.': '增加同时观看比赛的人数。',
    'Your Stadium earned you': '您的体育场赢得了您',
    'Idle Soccer Manager': '足球经理放置',
    'Join my Discord Server': '加入我的Discord服务器',
    'not': '不会',
    'Note: The Game does': '注意：游戏',
    'Min Avg. Stamina required': '最低平均耐力需要',
    'My Team is called': '我的团队被称为',
    'Full Team': '完整的团队',
    'Final Division': '最终分区',
    'Enter the next Country': '进入下一个国家',
    'Color Palette': '调色板',
    'Change you Notation to Zalgo': '把你的符号改成扎尔戈',
    'Buy your first Upgrade': '购买第一次升级',
    'Buy your first Player': '购买您的第一个球员',
    'The WORLD is watching': '全世界都在关注',
    'Super Speed': '超级速度',
    'Starting Out': '起步',
    'Rich? Not really...': '富有吗?不是真的…',
    'Promote into the next Division': '进入下一个分区',
    'Promote into the highest Division': '进入最高分区',
    'Give your Team Logo as many Colors as possible': '给你的团队的标志尽可能多的颜色',
    'Have 11 Players active in your Team': '你的球队有11名球员',
    'I am the Winner!': '我是赢家!',
    'I am the Master!': '我是大师!',
    'I am the Champion!': '我是冠军!',
    'Your performance in this match rewarded you': '您在这场比赛中的表现为您带来了回报',
    'Marriagecreek Warriors': '婚恋战士',
    'That\'s a lot of MONEY': '那是一大笔钱',
    'Decrease the Price of Players in the Market.': '降低市场中球员的价格。',
    'Get more Money per match played.': '每场比赛获得更多的钱。',
    'Increase the rate at which Players regenerate stamina.': '提高球员恢复耐力的速度。',
    'Increase the maximum Match Speed you can configure.': '增加您可以配置的最大比赛速度。',
    'You don\'t have any players in your Team. Consider buying some first in the Market.': '您的团队中没有任何球员。 考虑先在市场上购买一些。',
    'reward changes based on the division': '奖励的变化基于分区',
    'are disabled. Cleaning Utilities might clear Browser Storage. It is recommended to export your savegame': '被禁用。 清理实用程序可能会清除浏览器存储。 建议导出您的存档',
    'Term shown in Game Header': '游戏标题中显示的字词',
    'You need to have at least one Player in your Team': '你的团队中至少需要有一名球员',
    'You can add up to 11 Players to your Team. The overall strength of your Team is determined by the sum of your Players stats. Your Teams strength is multiplied by': '你最多可以为你的队伍添加11名球员。你的球队的整体实力是由你的球员统计数据的总和决定的。你的团队的力量会成倍增加',
    'Welcome to Idle Football Manager, a Game where you build your own Football Team and compete to become the champion!': '欢迎来到足球经理放置，在这个游戏中，你可以建立自己的足球队并竞争成为冠军!',
    'This is the Place where you can buy': '这是你可以买东西的地方',
    'This is the main part of the Game. Each League has': '这是游戏的主要部分。每个联盟都有',
    'the Tutorial in the Settings Menu!': '教程在设置菜单!',
    'The more Players that are active in your team, the higher your synergy is. Therefore, it is': '你的团队中活跃的球员越多，你的协同作用就越高。因此,它是',

    //原样
    'W': '胜',
    'L': '输',
    'GD': '净进球',
    'D': '平',
    'pts': '分数',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'AGG': '红牌率',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "ATT": "攻击",
    "DEF": "防御",
    "Synergy ": "协同 ",
    "Buy ($ ": "购买 ($ ",
    "Red Cards ": "红牌 ",
    "Match Speed": "比赛速度",
    "Matchday ": "比赛日 ",
    "My Football Club - ": "我的足球俱乐部 - ",
    "Teamfort Dreamers - ": "梦幻之队 - ",
    "Turn your Match Speed above ": "将您的比赛速度调高",
    "Have a Stadium Capacity of at least ": "拥有一个体育场容量至少是 ",
    "→ Currently ": "→ 当前 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    'Horrorcreek Club': '恐怖俱乐部',
    'Experiencecreek Runners': '埃里克森奔跑者',
    'Employmentton Runners': '埃普尔顿奔跑者',
    'Disasterdorf Kickers': '灾难村踢球者',
    "": "",
    "": "",
    "": "",
    "Carolyn Glenn": "卡罗琳·格伦",
    "Eloise Weber": "埃洛伊斯·韦伯",
    "Tanisha Burnett": "塔尼莎·伯纳特",
    "Tad Pacheco": "塔德·帕切科",
    "Sydney Simmons": "悉尼·西蒙斯",
    "Sondra Gilmore": "桑德拉·吉尔摩",
    'Vito Rose': '维托·罗斯',
    "Debbie Castro": "黛比·卡斯特罗",
    "Saundra Ward": "桑德拉·沃德",
    "Dennis Mckenzie": "丹尼斯·麦肯齐",
    "Corina Valdez": "科琳娜·瓦尔迪兹",
    "Bianca Oconnor": "比安卡·奥康纳",
    "Timothy Ferrell": "蒂莫西·费雷尔",
    "Timmy Blair": "蒂米·布莱尔",
    "Rosella Perez": "罗塞拉·佩雷斯",
    "Teresa Cannon": "特蕾莎·坎农",
    "Reggie Strong": "雷吉·斯特朗",
    "Phyllis Jimenez": "菲利斯·希门尼斯",
    "Nelda Henson": "内尔达·亨森",
    "Nola Valenzuela": "瓦蓝瑞·拉诺拉",
    "Mariano Rollins": "马里亚诺·罗林斯",
    "Luke Mclaughlin": "卢克·麦克劳林",
    'Charity Mccall': '里蒂·麦考尔',
    "Elsie House": "艾尔西之家",
    'Caleb Horn': '迦勒·霍恩',
    'Ira Glass': '伊拉·格拉斯',
    'Trinidad Knox': '尼达德·诺克斯',
    'Shelby Mccarty': '谢尔比·麦卡蒂',
    'Whitney Mcintosh': '惠特尼·麦金托什',
    'Willa Mcgowan': '薇拉·麦格万',
    'Alva Rowe': '阿尔瓦·罗维',
    'Dwayne Reyes': '德韦恩·雷耶斯',
    'Glenna Wheeler': '格伦娜·惠勒',
    'Jaclyn Vincent': '杰克琳·文森特',
    'Kennith Ashley': '肯尼思·阿什利',
    'Tyson Burns': '泰森·伯恩斯',
    'Jarrett Wilcox': '贾瑞特·威尔科克斯',
    'Kasey Odonnell': '凯西·奥多内尔',
    'Doris Byrd': '多丽丝·伯德',
    'Rosanna Drake': '罗莎娜·德雷克',
    'Brittney Simpson': '布兰妮·辛普森',
    'Cody Anthony': '科迪·安东尼',
    'Lynda Jarvis': '琳达·贾维斯',
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    " Fans (guaranteed viewers": "球迷（保证观众",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^ ([\d\.,]+)$/,
    /^([\d\.,]+)$/,
    /^(\d+)\:(\d+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Refresh in (\d+) Matchday\(s$/, '还有 $1 个比赛日刷新(✌️'],
    [/^ x([\d\.]+), DEF x([\d\.]+)$/, ' x$1, 防御 x$2'],
    [/^Have at least (.+) Fans$/, '拥有至少 $1 球迷'],
    [/^Have at least (.+) \$$/, '拥有至少 $1 \$'],
    [/^→ Lose ÷(.+) Stamina per Game$/, '→ 每场比赛失去 ÷$1 耐力'],
    [/^→ x(.+) Stamina Regeneration$/, '→ x$1 耐力恢复'],
    [/^→ x(.+) Chance to get a Red Card$/, '→ x$1 几率得到红牌'],
    [/^→ (.+) to regenerate$/, '→ $1 恢复'],
    [/^\((.+) left$/, '\($1 剩余'],
    [/^🏆 (.+) League \(Division (.+)$/, '🏆 $1 联赛 \(分区 $2'],
    [/^(.+) \$ per Ticket → (.+) \$ possible$/, '每张票 $1 \$ → 可能有 $2 \$'],
    [/^(.+) \/ (.+) watching$/, '$1 \/ $2 在看'],
    [/^You have (.+) \$$/, '你有 $1 \$'],
    [/^You now have (.+) \$$/, '你现在有 $1 \$'],
    [/^Sell \((.+) \$$/, '出售 \($1 \$'],
    [/^ ÷([\d\.]+), DEF ÷([\d\.]+)$/, ' ÷$1, 防御 ÷$2'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);