/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Standard': '标准',
    'Stripe Color': '条纹颜色',
    'Upgrades': '升级',
    'Tutorial': '教程',
    'Visit my Website': '访问我的网站',
    'Your Team': '你的团队',
    'Zalgo': '扎尔戈',
    'Team Settings': '团队设置',
    'Adjust the Speed of the Game': '调整游戏速度',
    'Aggressiveness': '进取心',
    'always restart': '总是重启',
    'and on new Seasons.': '以及新赛季。',
    'cookies or storage': 'Cookie或本地存储',
    'Download Savegame': '下载游戏存档',
    'Each Player has 4 Stats': '每个玩家有4个属性',
    'Engineering': '工程符号',
    'Exit Tutorial': '退出教程',
    'Export Game': '导出存档',
    'Game Settings': '游戏设置',
    'Football': '足球',
    'HARD RESET': '硬重置',
    'Idle Football Manager': '足球经理放置',
    'Import Game': '导入存档',
    'Letters': '字母',
    'League': '联盟',
    'Market': '市场',
    'Match Autoplay': '自动进行比赛',
    'Mixed engineering': '混合工程',
    'Mixed scientific': '混合科学',
    'new Players': '新玩家',
    'Player Market': '玩家市场',
    'Prime': '素数',
    'Restart Tutorial': '重启教程',
    'Roman': '罗马',
    'Save Management': '保存管理',
    'Scientific': '科学计数法',
    'Sides': '双方',
    'Match': '比赛',
    'Team': '团队',
    'Brackets': '括号',
    'Clock': '时钟',
    'Colors': '颜色',
    'Dots': '圆点',
    'Blind': '盲文',
    'Bar': '酒吧',
    'Hex': '十六进制',
    'Icon': '图标',
    'Imperial': '英制',
    'Infinity': '无限',
    'Logarithm': '对数',
    'Refill Team after Match': '赛后补充队员',
    'Social': '社交',
    'Strategy': '策略',
    'Refresh in 3 Matchday(s': '在3个比赛日刷新(',
    'STA': '属性',
    'Move from Team': '离开团队',
    'My Football Club': '我的足球俱乐部',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'You don\'t have any players in your Team. Consider buying some first in the Market.': '您的团队中没有任何球员。 考虑先在市场上购买一些。',
    'reward changes based on the division': '奖励的变化基于部门',
    'are disabled. Cleaning Utilities might clear Browser Storage. It is recommended to export your savegame': '被禁用。 清理实用程序可能会清除浏览器存储。 建议导出您的存档',
    'Term shown in Game Header': '游戏标题中显示的字词',
    'You need to have at least one Player in your Team': '你的团队中至少需要有一名队员',
    'You can add up to 11 Players to your Team. The overall strength of your Team is determined by the sum of your Players stats. Your Teams strength is multiplied by': '你最多可以为你的队伍添加11名球员。你的球队的整体实力是由你的球员统计数据的总和决定的。你的团队的力量会成倍增加',
    'Welcome to Idle Football Manager, a Game where you build your own Football Team and compete to become the champion!': '欢迎来到足球经理放置，在这个游戏中，你可以建立自己的足球队并竞争成为冠军!',
    'This is the Place where you can buy': '这是你可以买东西的地方',
    'This is the main part of the Game. Each League has': '这是游戏的主要部分。每个联盟都有',
    'the Tutorial in the Settings Menu!': '教程在设置菜单!',
    'The more Players that are active in your team, the higher your synergy is. Therefore, it is': '你的团队中活跃的球员越多，你的协同作用就越高。因此,它是',

    //原样
    'Caleb Horn': '迦勒·霍恩',
    'Charity Mccall': '里蒂·麦考尔',
    'Ira Glass': '伊拉·格拉斯',
    'Trinidad Knox': '尼达德·诺克斯',
    'Shelby Mccarty': '谢尔比·麦卡蒂',
    'Whitney Mcintosh': '惠特尼·麦金托什',
    'Willa Mcgowan': '薇拉·麦格万',
    'Alva Rowe': '阿尔瓦·罗维',
    'Dwayne Reyes': '德韦恩·雷耶斯',
    'Glenna Wheeler': '格伦娜·惠勒',
    'Jaclyn Vincent': '杰克琳·文森特',
    'Kennith Ashley': '肯尼思·阿什利',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "ATT": "攻击",
    "DEF": "防御",
    "Synergy ": "协同 ",
    "Buy ($ ": "购买 ($ ",
    "Red Cards ": "红牌 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^ x([\d\.]+), DEF x([\d\.]+)$/, ' x$1, 防御 x$2'],
    [/^You have (.+) \$$/, '你有 $1 \$'],
    [/^Sell \((.+) \$$/, '出售 \($1 \$'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);