/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Stripe Color': '条纹颜色',
    'Upgrades': '升级',
    'Tutorial': '教程',
    'Visit my Website': '访问我的网站',
    'Your Team': '你的团队',
    'Team Settings': '团队设置',
    'Adjust the Speed of the Game': '调整游戏速度',
    'Aggressiveness': '红牌率',
    'always restart': '总是重启',
    'and on new Seasons.': '以及新赛季。',
    'cookies or storage': 'Cookie或本地存储',
    'Download Savegame': '下载游戏存档',
    'Each Player has 4 Stats': '每个球员有4个属性',
    'Exit Tutorial': '退出教程',
    'Export Game': '导出存档',
    'Game Settings': '游戏设置',
    'Football': '足球',
    'HARD RESET': '硬重置',
    'Idle Football Manager': '足球经理放置',
    'Import Game': '导入存档',
    'League': '联盟',
    'Market': '市场',
    'Match Autoplay': '自动进行比赛',
    'new Players': '新球员',
    'Player Market': '球员市场',
    'Restart Tutorial': '重启教程',
    'Save Management': '保存管理',
    'Sides': '双方',
    'Match': '比赛',
    'Team': '团队',
    'Colors': '颜色',
    'Icon': '图标',
    'Refill Team after Match': '赛后补充球员',
    'Social': '社交',
    'Strategy': '策略',
    'STA': '耐力',
    'Move from Team': '离开团队',
    'My Football Club': '我的足球俱乐部',
    'Match Rewards': '比赛奖励',
    'Play next Match': '进行下一场比赛',
    'Recommendationheim Warriors': '推荐海战勇士',
    'Richheim United': '里希海姆联',
    'Screwdorf Kickers': '斯卡特多夫踢球者',
    'Start': '开始',
    'Teamfort Dreamers': '梦幻之队',
    'Energy Drink': '能量饮料',
    'Soccer': '足球',
    'save if': '保存如果',
    'Unlock the Stadium': '解锁体育场',
    'Someone\'s watching': '有人在看',
    'Games': '游戏',
    'Upgradealicious': '可升级',
    'Very Famous': '非常有名',
    'Win your first match': '赢得你的第一场比赛',
    '→ Play next Match': '→ 进行下一场比赛',
    'Market Strategy': '市场策略',
    'Match Ended': '比赛结束',
    'Move to Team': '加入团队',
    'You are already in a Match.': '您已经在比赛中。',
    'Kinda Famous': '金田名品',
    'Goals': '进球',
    'Number Format': '数字格式',
    'often': '经常',
    'Stadium': '体育场',
    'Stadium Capacity': '体育场容量',
    'Pricing Tactics': '定价策略',
    'Attack': '攻击',
    'Defense': '防御',
    'Stamina': '耐力',
    'Around the World': '环游世界',
    'backup your progress': '备份您的进度',
    'be enough to buy the Moon': '足以买月亮',
    'configure': '配置',
    'Enter the 3rd Country': '进入第三个国家',
    'Ludicrous Speed': '可笑的速度',
    'might': '可能',
    'promote': '提升',
    'refreshes every few Matchdays': '每隔几个比赛日刷新一次',
    'Synergy': '协同作用',
    'ten divisions': '10地区',
    'Hold Shift to sell Players': '按住Shift出售球员',
    'Training': '训练',
    'Train': '训练',
    'Training Factor': '训练因子',
    'Max': '最大',
    'more money': '更多的钱',
    'random amount': '随机数量',
    'Stop Training': '停止训练',
    'Players train faster. No doping included!': '球员训练速度更快。不包括兴奋剂!',
    'Players in Training': '球员在训练中',
    'every second': '每秒',
    'GOALUnited': '目标团结',
    'Tired of always throwing players out after each season? You can now': '厌倦了在每个赛季结束后总是将球员赶出场吗？ 你现在可以',
    'select a training': '选择一个训练',
    'unleash their potential': '释放他们的潜力',
    'upgrade': '升级',
    'FootForce TV': '足力电视',
    'Futebol Mágico': '魔术足球',
    'by training them.': '通过训练他们。',
    '. You can also': '。 你也可以',
    'Every good Football Team needs a Stadium! Building a stadium earns you': '每个好的足球队都需要一个体育场！ 建立体育场可以为您带来收益',
    'after each Match.': '每次比赛之后。',
    'fans': '球迷',
    'some': '某个',
    'relegate': '贬谪',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Render TV Screens (decreases Performance)': '渲染电视屏幕（降低性能）',
    'You are in': '你在',
    'No one knows its name, its Flag or anything else about it. All we know is that there\'s an uncountable amount of those countries, and each of them has a Football League. How far can you go? Good Luck!': '没有人知道它的名字，旗帜或其他任何有关它的信息。 我们所知道的是，这些国家数量众多，每个国家都有一个足球联赛。 你能走多远？ 祝你好运！',
    'multiple aspects of training to increase the potential even more.': '训练的各个方面，以增加更多的潜力。',
    'Just move them to training from the \"Team\" tab and': '只需将他们从“团队”标签中移至培训，然后',
    'Imageberg Dreamers': '图片伯格梦想家',
    'while a Match is running, based on its win reward. Also,': '在比赛进行时，根据比赛获胜奖励。 还，',
    'Wanna see me play a match? Wanna see me do it again?': '想看我比赛吗?想看我再做一次吗?',
    'TV Channels provide an': '电视频道提供',
    'TV': '电视',
    'TV Channels': '电视频道',
    'to boost your income even further.': '来进一步提高你的收入。',
    'There also are': '也有',
    'Statistical Recognition': '统计识别',
    'Match Rewards get multiplied': '比赛奖励成倍增加',
    'Locked': '未解锁',
    'Increase the Match Rewards by a percentage of Stadium Rewards.': '以球场奖励的百分比来增加比赛奖励。',
    'Increase max Match Speed.': '提高最大比赛速度。',
    'Cool Ads and nice Commentary': '很酷的广告和不错的评论',
    'Channels pay you more Money each second.': '频道每秒钟支付给你更多的钱。',
    'Channels': '频道',
    'by a certain amount.': '一定程度上。',
    'Beyond Speed': '除了速度',
    'additional Upgrades': '额外的升级',
    'additional source of income': '额外收入来源',
    '. When buying (or contracting) a TV Channel, you get paid for': '。当你购买(或签约)一个电视频道时，你得到了报酬',
    'Discipline! Discipline!': '纪律!纪律!',
    'Learning Curve': '学习曲线',
    'Infinite Potential': '无限潜力',
    'General Training': '常规训练',
    'Aggressivity Training': '攻击性训练',
    'Increase Attack and Defense additively each time to let your players just perform better than before.': '每次都增加攻击和防御，使您的球员表现比以前更好。',
    'The Stat increase after General Training is slightly exponential.': '常规训练后属性的增加是指数级的。',
    'The Stat increase after General Training is higher.': '常规训练后的属性增加更高。',
    'Teach your Players that kicking legs instead of footballs is not good. Cut Aggressiveness by 1 % each time.': '告诉你的球员踢腿而不踢足球是不好的。每次减少1%的攻击性。',
    'Stamina Training': '耐力训练',
    'Let your Players run around the pitch to train their Stamina by 1 each time.': '让您的球员在球场上奔跑，以使其每次耐力训练一次。',
    'you have (fans are guaranteed viewers).': '您有（球迷是观众的保证）。',
    'When a Match begins, a': '当一场比赛开始时，',
    'to boost your Stadium income.': '以增加您的体育场收入。',
    'of viewers come to watch your Match (0% - 100%) plus all the': '的观众来观看您的比赛（0％-100％）以及所有',
    'U Got Gud': '你得到了上帝',
    'U Got God': '你有上帝庇佑',
    'Unlock TV Channels by Reaching Division 2': '解锁电视频道通过第2地区',
    'Unlock Player Training by Reaching Division 5': '解锁球员训练通过第5地区',
    'The WORLD WORLD is watching': '全世界都在观看',
    'the Tutorial in the Settings Menu! You can also use it to': '设置菜单中的教程！ 您也可以使用它来',
    'the Game to your needs and to': '游戏满足您的需求和',
    'imagine We had 7.8 Billion Earths, with 7.8 Billion people each.': '想象一下，我们有78亿个地球，每个地球上都有78亿人口。',
    'Have a Player with a sell price of over 1.00 Qt, which': '拥有一个售价超过1.00 Qt的球员，',
    'Nowhereia': '无处',
    'Next Country': '下一个国家',
    'Countries': '国家',
    'Anti-Football Nation': '反足球国家',
    'You need to become champion in Division 1 at least once.': '您至少需要在1级联赛中成为冠军。',
    'You can re-buy sold Players': '您可以重新购买已售出的球员',
    'you are in.': '你在。',
    'while they are still there.': '他们还在那里的时候',
    'Upgrades are bought with Money and let you boost different aspects of the Game.': '升级是通过花钱购买的，可让您增强游戏的各个方面。',
    'to your liking. At the end of a Match, you get money based on if you won, drew or lost the game. The': '根据您的喜好。 在比赛结束时，您将根据赢，输或输的游戏来获利。 这',
    'to get more Information about the Team. You can also hover it for a moment to see its Attack and Defense': '以获得有关团队的更多信息。 您也可以将鼠标悬停一会儿以查看其攻击和防御',
    'to get a Stat Breakdown.': '以获得统计数据细分。',
    'to be able to buy Upgrades.': '才能购买升级道具。',
    'to a lower division (red cells).': '到较低的分区(红色格子)。',
    'to a higher division (green cells) or': '到一个更高的分区(绿色格子)或',
    'The Market': '市场',
    'than one strong player.': '而不是一个强大的球员。',
    'ressiveness (Chance to get a Red Card) and': '抵触情绪（获得红牌的几率）和',
    'refreshes every few Matchday': '每隔几个比赛日刷新一次',
    'mina (How fast players lose and regenerate Stamina). Stamina passively fills every second while a player is not playing.': 'mina(玩家失去和恢复耐力的速度)。当玩家不玩游戏时，耐力会被动地占据每一秒。',
    'It\'s just an ordinary Country, as ordinary as it can be. There\'s nothing special about it. They': '就像一个普通的国家一样，它只是一个普通的国家。 没什么特别的。 他们',
    'In the Match tab, you can watch the Game live.': '在“比赛”选项卡中，您可以实时观看比赛。',
    'for your Team. The more expensive a player is, the more money you have to pay.': '为您的团队。 球员越贵，您必须支付的钱就越多。',
    'don\'t even have a unique Name.': '甚至没有唯一的名称。',
    'Click on a Team Name': '点击团队名称',
    'Click on a Players name': '单击球员名称',
    'better to have more weak players': '最好有更多弱小的球员',
    '. At the end of the Season, you can either': '。在赛季结束时，你可以选择',
    ', of which each has': '，每个人都有',
    'You can': '你可以',
    'freely navigate inside the Game': '在游戏中自由导航',
    'while the Tutorial Window is open. Feel free to try out the mechanics on the go! Click the (X) on the top right of the window to view the next page': '当“教程窗口”打开时。 随时随地尝试各种机制！ 单击窗口右上角的（X）查看下一页',
    '→ Modified by Stamina': '→ 根据耐力变化',
    '🏟 Your Stadium': '🏟 你的体育场',
    'The Famous Factor': '著名因子',
    'More people decide to become a fan.': '越来越多的人决定成为球迷。',
    'Increase the Price for each Ticket. Don\'t worry, this won\'t decrease attendance.': '增加每张票的价格。 不用担心，这不会减少出勤率。',
    'Increase the Amount of people that can watch the match at once.': '增加同时观看比赛的人数。',
    'Your Stadium earned you': '您的体育场赢得了您',
    'Idle Soccer Manager': '足球经理放置',
    'Join my Discord Server': '加入我的Discord服务器',
    'not': '不会',
    'Note: The Game does': '注意：游戏',
    'Min Avg. Stamina required': '最低平均耐力需要',
    'My Team is called': '我的团队被称为',
    'Full Team': '完整的团队',
    'Final Division': '最终分区',
    'Enter the next Country': '进入下一个国家',
    'Color Palette': '调色板',
    'Change your Notation to Zalgo': '把你的符号改成Zalgo',
    'Buy your first Upgrade': '购买第一次升级',
    'Buy your first Player': '购买您的第一个球员',
    'The WORLD is watching': '全世界都在关注',
    'Super Speed': '超级速度',
    'Starting Out': '起步',
    'Rich? Not really...': '富有吗?不是真的…',
    'Promote into the next Division': '进入下一个分区',
    'Promote into the highest Division': '进入最高分区',
    'Give your Team Logo as many Colors as possible': '给你的团队的标志尽可能多的颜色',
    'Have 11 Players active in your Team': '你的球队有11名球员',
    'I am the Winner!': '我是赢家!',
    'I am the Master!': '我是大师!',
    'I am the Champion!': '我是冠军!',
    'Your performance in this match rewarded you': '您在这场比赛中的表现为您带来了回报',
    'Marriagecreek Warriors': '婚恋战士',
    'That\'s a lot of MONEY': '那是一大笔钱',
    'Decrease the Price of Players in the Market.': '降低市场中球员的价格。',
    'Get more Money per match played.': '每场比赛获得更多的钱。',
    'Increase the rate at which Players regenerate stamina.': '提高球员恢复耐力的速度。',
    'Increase the maximum Match Speed you can configure.': '增加您可以配置的最大比赛速度。',
    'You don\'t have any players in your Team. Consider buying some first in the Market.': '您的团队中没有任何球员。 考虑先在市场上购买一些。',
    'reward changes based on the division': '奖励的变化基于分区',
    'are disabled. Cleaning Utilities might clear Browser Storage. It is recommended to export your savegame': '被禁用。 清理实用程序可能会清除浏览器存储。 建议导出您的存档',
    'Term shown in Game Header': '游戏标题中显示的字词',
    'You need to have at least one Player in your Team': '你的团队中至少需要有一名球员',
    'You can add up to 11 Players to your Team. The overall strength of your Team is determined by the sum of your Players stats. Your Teams strength is multiplied by': '你最多可以为你的队伍添加11名球员。你的球队的整体实力是由你的球员统计数据的总和决定的。你的团队的力量会成倍增加',
    'Welcome to Idle Football Manager, a Game where you build your own Football Team and compete to become the champion!': '欢迎来到足球经理放置，在这个游戏中，你可以建立自己的足球队并竞争成为冠军!',
    'This is the Place where you can buy': '这是你可以买东西的地方',
    'This is the main part of the Game. Each League has': '这是游戏的主要部分。每个联盟都有',
    'the Tutorial in the Settings Menu!': '教程在设置菜单!',
    'The more Players that are active in your team, the higher your synergy is. Therefore, it is': '你的团队中活跃的球员越多，你的协同作用就越高。因此,它是',

    //原样
    'W': '胜',
    'L': '输',
    'GD': '净进球',
    'D': '平',
    'pts': '分数',
//    取消计数法汉化，因为会报错
//    'Letters': '字母',
//    'Standard': '标准',
//    'Dots': '圆点',
//    'Blind': '盲文',
//    'Bar': '酒吧',
//    'Hex': '十六进制',
//    'Imperial': '英制',
//    'Infinity': '无限',
//    'Logarithm': '对数',
//    'Scientific': '科学计数法',
//    'Mixed engineering': '混合工程',
//    'Mixed scientific': '混合科学',
//    'Brackets': '括号',
//    'Cancer': '癌症',
//    'Engineering': '工程符号',
//    'Clock': '时钟',
//    'Prime': '素数',
//    'Roman': '罗马',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'AGG': '红牌率',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "ATT": "攻击",
    "DEF": "防御",
    "Synergy ": "协同 ",
    "Buy ($ ": "购买 ($ ",
    "Red Cards ": "红牌 ",
    "Match Speed": "比赛速度",
    "Matchday ": "比赛日 ",
    "My Football Club - ": "我的足球俱乐部 - ",
    "Teamfort Dreamers - ": "梦幻之队 - ",
    "Turn your Match Speed above ": "将您的比赛速度调高",
    "Have a Stadium Capacity of at least ": "拥有一个体育场容量至少是 ",
    "→ Currently ": "→ 当前 ",
    "Country ": "国家 ",
    "Channel ": "频道 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Have a player with a Training Factor of over ": "有一个球员的训练因子超过",
    'Horrorcreek Club': '恐怖俱乐部',
    'Experiencecreek Runners': '埃里克森奔跑者',
    'Employmentton Runners': '埃普尔顿奔跑者',
    'Disasterdorf Kickers': '灾难村踢球者',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Rosemarie Hale": "罗斯玛丽·黑尔",
    "Henry Mercer": "亨利·默瑟",
    "Anderson Franco": "安德森·佛朗哥",
    "Alphonse Rasmussen": "阿方斯·拉斯穆森",
    "Agnes Walker": "艾格尼丝·沃克",
    "Stonks": "斯通克斯",
    "Git Gud": "吉特·古德",
    "Carolyn Glenn": "卡罗琳·格伦",
    "Eloise Weber": "埃洛伊斯·韦伯",
    "Tanisha Burnett": "塔尼莎·伯纳特",
    "Tad Pacheco": "塔德·帕切科",
    "Sydney Simmons": "悉尼·西蒙斯",
    "Sondra Gilmore": "桑德拉·吉尔摩",
    'Vito Rose': '维托·罗斯',
    "Debbie Castro": "黛比·卡斯特罗",
    "Saundra Ward": "桑德拉·沃德",
    "Dennis Mckenzie": "丹尼斯·麦肯齐",
    "Corina Valdez": "科琳娜·瓦尔迪兹",
    "Bianca Oconnor": "比安卡·奥康纳",
    "Timothy Ferrell": "蒂莫西·费雷尔",
    "Timmy Blair": "蒂米·布莱尔",
    "Rosella Perez": "罗塞拉·佩雷斯",
    "Teresa Cannon": "特蕾莎·坎农",
    "Reggie Strong": "雷吉·斯特朗",
    "Phyllis Jimenez": "菲利斯·希门尼斯",
    "Nelda Henson": "内尔达·亨森",
    "Nola Valenzuela": "瓦蓝瑞·拉诺拉",
    "Mariano Rollins": "马里亚诺·罗林斯",
    "Luke Mclaughlin": "卢克·麦克劳林",
    'Charity Mccall': '里蒂·麦考尔',
    "Elsie House": "艾尔西之家",
    'Caleb Horn': '迦勒·霍恩',
    'Ira Glass': '伊拉·格拉斯',
    'Trinidad Knox': '尼达德·诺克斯',
    'Shelby Mccarty': '谢尔比·麦卡蒂',
    'Whitney Mcintosh': '惠特尼·麦金托什',
    'Willa Mcgowan': '薇拉·麦格万',
    'Alva Rowe': '阿尔瓦·罗维',
    'Dwayne Reyes': '德韦恩·雷耶斯',
    'Glenna Wheeler': '格伦娜·惠勒',
    'Jaclyn Vincent': '杰克琳·文森特',
    'Kennith Ashley': '肯尼思·阿什利',
    'Tyson Burns': '泰森·伯恩斯',
    'Jarrett Wilcox': '贾瑞特·威尔科克斯',
    'Kasey Odonnell': '凯西·奥多内尔',
    'Doris Byrd': '多丽丝·伯德',
    'Rosanna Drake': '罗莎娜·德雷克',
    'Brittney Simpson': '布兰妮·辛普森',
    'Cody Anthony': '科迪·安东尼',
    'Lynda Jarvis': '琳达·贾维斯',
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    " Fans (guaranteed viewers": "球迷（保证观众",
    " to Attack and Defense": "以攻防",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^ ([\d\.,]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+) T$/,
    /^([\d\.,]+) Qt$/,
    /^([\d\.,]+) Qa$/,
    /^ ([\d\.,]+) Qa$/,
    /^([\d\.,]+) TVg$/,
    /^([\d\.,]+) DVg$/,
    /^ ([\d\.,]+) TVg$/,
    /^(\d+)\:(\d+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Refresh in (\d+) Matchday\(s$/, '还有 $1 个比赛日刷新(✌️'],
    [/^ x([\d\.]+), DEF x([\d\.]+)$/, ' x$1, 防御 x$2'],
    [/^([\d\.]+) Matchdays$/, '$1 比赛日'],
    [/^Paying (.+) \$ per second while in Match and multiplying Match Rewards by x(.+)$/, '在比赛期间每秒支付 $1 \$，并将比赛奖励乘以 x$2'],
    [/^Have at least (.+) Fans$/, '拥有至少 $1 球迷'],
    [/^Have at least (.+) \$$/, '拥有至少 $1 \$'],
    [/^→ Lose ÷(.+) Stamina per Game$/, '→ 每场比赛失去 ÷$1 耐力'],
    [/^→ x(.+) Stamina Regeneration$/, '→ x$1 耐力恢复'],
    [/^→ x(.+) Chance to get a Red Card$/, '→ x$1 几率得到红牌'],
    [/^→ (.+) to regenerate$/, '→ $1 恢复'],
    [/^This is your Starting Point. People here don't even really play Football, and are not interested in it. \n(.+)Teams here aren't very good, a good way for you to get going!$/, '这是你的起点。这里的人甚至都不怎么踢足球，对足球也不感兴趣。这里的团队不是很好，对你来说是开始的好方法!'],
    [/^They do play Football, but they really dislike it. They still play it, for some reason.\n(.+)They are better than in Nowhereia, but it won't be a Problem for you.$/, '他们确实踢足球，但他们真的不喜欢。出于某种原因，他们仍然在玩这款游戏。他们总比在哪儿都好，但这对你来说不是问题。'],
    [/^\((.+) left$/, '\($1 剩余'],
    [/^🏆 (.+) League \(Division (.+)$/, '🏆 $1 联赛 \(分区 $2'],
    [/^(.+) \$ per Ticket → (.+) \$ possible$/, '每张票 $1 \$ → 可能有 $2 \$'],
    [/^(.+) \/ (.+) watching$/, '$1 \/ $2 在看'],
    [/^You have (.+) \$$/, '你有 $1 \$'],
    [/^You now have (.+) \$$/, '你现在有 $1 \$'],
    [/^Sell \((.+) \$$/, '出售 \($1 \$'],
    [/^ ÷([\d\.]+), DEF ÷([\d\.]+)$/, ' ÷$1, 防御 ÷$2'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);